### ISSUE TITLE
Could not update data -

### ISSUE THREAD

**Issue by jordanbean1** [snicker/skydrop_hass#1]
## Version of the custom_component
0.0.1

## Configuration

```yaml

skydrop:
    client_key: !secret skydrop_client_key
    client_secret: !secret skydrop_client_secret

```

## Describe the bug
After populating client_key, client_secret & grant code (when prompted), the log indicates that there was an error when trying to update data from the Skydrop API. I can see in the `config/.storage/skydrop_store` file that both an "access" & "refresh" token were retrieved, with a expiry that is still valid.

I tried configuring both with the Integrations page as well as the configuration.yaml, same issue.

Also, is there a "specific" redirect_uri that should be added to the Skydrop Application registration or will any redirect_uri work (such as "https://www.getpostman.com/oauth2/callback")?

## Debug log

```text

2020-05-04 22:28:56 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for skydrop which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-04 22:29:09 DEBUG (MainThread) [homeassistant.bootstrap] Setting up {'input_boolean', 'scene', 'neato', 'input_select', 'websocket_api', 'sun', 'switch', 'device_tracker', 'unifi', 'ring', 'zone', 'ssdp', 'script', 'persistent_notification', 'ffmpeg', 'default_config', 'mqtt', 'media_player', 'glances', 'roku', 'input_text', 'zeroconf', 'sensor', 'history', 'hacs', 'skydrop', 'input_datetime', 'input_number', 'webhook', 'map', 'device_automation', 'http', 'climate', 'alarm_control_panel', 'frontend', 'tesla', 'zwave', 'system_health', 'onboarding', 'discovery', 'light', 'conversation', 'updater', 'group', 'notify', 'water_heater', 'ipp', 'lovelace', 'mobile_app', 'api', 'pi_hole', 'binary_sensor', 'panel_custom', 'config', 'met'}
2020-05-04 22:29:11 INFO (MainThread) [homeassistant.setup] Setting up skydrop
2020-05-04 22:29:11 INFO (MainThread) [homeassistant.setup] Setup of domain skydrop took 0.0 seconds.
2020-05-04 22:29:15 INFO (MainThread) [custom_components.skydrop] skydrop 0.0.1 https://github.com/snicker/skydrop_hass/issues starting...
2
2020-05-04 22:29:51 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event hacs/repository[L]: id=1337, action=registration, repository=snicker/skydrop_hass, repository_id=None>
2020-05-04 22:30:23 ERROR (MainThread) [custom_components.skydrop] Could not update data - 
2020-05-04 22:30:23 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=skydrop>
2020-05-04 22:30:23 INFO (MainThread) [homeassistant.components.switch] Setting up switch.skydrop
2020-05-04 22:30:23 DEBUG (MainThread) [homeassistant.bootstrap] Setting up {'camera', 'alexa', 'auth', 'person', 'hassio', 'automation', 'search'}
2020-05-04 22:30:23 DEBUG (SyncWorker_15) [custom_components.skydrop.switch] Added []
2020-05-04 22:30:23 INFO (MainThread) [homeassistant.setup] Setting up hassio
2020-05-04 22:30:23 INFO (MainThread) [custom_components.skydrop.switch] 0 Skydrop switch(es) added
20
2020-05-04 22:30:30 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.1765045680] Sending {'id': 13, 'type': 'result', 'success': True, 'result': {'latitude': 30.181767792090575, 'longitude': -95.49165129661561, 'elevation': 50, 'unit_system': {'length': 'mi', 'mass': 'lb', 'pressure': 'psi', 'temperature': '°F', 'volume': 'gal'}, 'location_name': 'Home', 'time_zone': 'America/Chicago', 'components': {'binary_sensor.tesla', 'neato', 'sun', 'switch.wake_on_lan', 'device_tracker', 'unifi', 'script', 'automation', 'sensor.neato', 'default_config', 'mqtt', 'glances', 'vacuum.neato', 'logger', 'switch.neato', 'remote', 'device_tracker.tesla', 'http', 'frontend', 'scene.homeassistant', 'sensor.zwave', 'sensor.yr', 'light.ring', 'discovery', 'device_tracker.mobile_app', 'light', 'search', 'group', 'notify', 'recorder', 'camera.ring', 'water_heater.econet', 'api', 'pi_hole', 'panel_custom', 'notify.group', 'input_boolean', 'switch.template', 'climate.mqtt', 'switch', 'camera.neato', 'sensor.mqtt', 'tts', 'roku', 'switch.zwave', 'stt', 'wake_on_lan', 'history', 'webhook', 'device_automation', 'sensor.command_line', 'weather.met', 'weather', 'binary_sensor.mobile_app', 'alarm_control_panel.mqtt', 'sensor.template', 'binary_sensor.mqtt', 'sensor.mobile_app', 'hassio', 'light.zwave', 'updater', 'light.mqtt', 'logbook', 'person', 'fan', 'lock.zwave', 'scene', 'sensor.systemmonitor', 'sensor.tesla', 'persistent_notification', 'ffmpeg', 'media_player', 'auth', 'input_text', 'sensor', 'switch.skydrop', 'skydrop', 'vacuum', 'media_player.roku', 'map', 'alexa', 'binary_sensor.zwave', 'onboarding', 'sensor.ipp', 'sensor.hacs', 'cover', 'sensor.pi_hole', 'lock', 'ipp', 'switch.tesla', 'mobile_app', 'config', 'cloud', 'camera', 'input_select', 'lock.tesla', 'websocket_api', 'binary_sensor.ring', 'switch.ring', 'zone', 'ssdp', 'ring', 'system_log', 'binary_sensor.updater', 'zeroconf', 'hacs', 'input_datetime', 'climate.zwave', 'input_number', 'climate', 'alarm_control_panel', 'tesla', 'notify.mobile_app', 'climate.tesla', 'zwave', 'system_health', 'binary_sensor.cloud', 'conversation', 'water_heater', 'fan.zwave', 'homeassistant', 'lovelace', 'sensor.ring', 'stream', 'remote.roku', 'binary_sensor', 'cover.zwave', 'met', 'switch.mqtt'}, 'config_dir': '/config', 'whitelist_external_dirs': {'/config/www'}, 'version': '0.109.3', 'config_source': 'storage', 'safe_mode': False}}
2020-05-04 22:30:30 DEBUG (MainThread) [homeassistant.helpers.translation] Cache miss for en, state: binary_sensor.tesla, neato, sun, switch.wake_on_lan, device_tracker, unifi, script, automation, sensor.neato, default_config, mqtt, glances, vacuum.neato, logger, switch.neato, remote, device_tracker.tesla, http, frontend, scene.homeassistant, sensor.zwave, sensor.yr, light.ring, discovery, device_tracker.mobile_app, light, search, group, notify, recorder, camera.ring, water_heater.econet, api, pi_hole, panel_custom, notify.group, input_boolean, switch.template, climate.mqtt, switch, camera.neato, sensor.mqtt, tts, roku, switch.zwave, stt, wake_on_lan, history, webhook, device_automation, sensor.command_line, weather.met, weather, binary_sensor.mobile_app, alarm_control_panel.mqtt, sensor.template, binary_sensor.mqtt, sensor.mobile_app, hassio, light.zwave, updater, light.mqtt, logbook, person, fan, lock.zwave, scene, sensor.systemmonitor, sensor.tesla, persistent_notification, ffmpeg, media_player, auth, input_text, sensor, switch.skydrop, skydrop, vacuum, media_player.roku, map, alexa, binary_sensor.zwave, onboarding, sensor.ipp, sensor.hacs, cover, sensor.pi_hole, lock, ipp, switch.tesla, mobile_app, config, cloud, camera, input_select, lock.tesla, websocket_api, binary_sensor.ring, switch.ring, zone, ssdp, ring, system_log, binary_sensor.updater, zeroconf, hacs, input_datetime, climate.zwave, input_number, climate, alarm_control_panel, tesla, notify.mobile_app, climate.tesla, zwave, system_health, binary_sensor.cloud, conversation, water_heater, fan.zwave, homeassistant, lovelace, sensor.ring, stream, remote.roku, binary_sensor, cover.zwave, met, switch.mqtt
2020-05-04 22:30:35 WARNING (MainThread) [homeassistant.helpers.translation] skydrop: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this 
2020-05-04 22:30:38 DEBUG (SyncWorker_10) [homeassistant.util.json] JSON file not found: /config/custom_components/skydrop/.translations/switch.en.json


```

**Comment by cappers278** [comment]
Yes I had the same issue.

**Comment by 9kon** [comment]
Also have same issue.

**Comment by 9kon** [comment]
I do get a acces token. 
From the skydrop_store file i have

"
{
    "data": {
        "access": "37f40200f38b5a49267b91864f797305ad7bc16d",
        "expires": 1592752009,
        "refresh": "e753f9995324dbe5b594bd45337799f656f175fb"
    },
    "key": "skydrop_store",
    "version": "0.0.1"
}
"
So it apears that it autorizies correctly, but i still get the error.

"
Log Details (ERROR)
Logger: custom_components.skydrop
Source: custom_components/skydrop/__init__.py:188
Integration: SkydropHASS (documentation)
First occurred: 7:18:33 PM (1 occurrences)
Last logged: 7:18:33 PM

Could not update data -
"

**Comment by cappers278** [comment]
@snicker Would you know why we get the "could not update data" error?  Not urgent, but thought I'd ping you in case it's an easy remedy.

**Comment by 9kon** [comment]
@snicker Just looking through the files i can see that it is calling methods that only exits in your skydroppy repo does both have to be installed?

**Comment by 9kon** [comment]
Ahh I see that im correct `import skydroppy` is in there, can someone explain to me how to install skydroppy in hass.io so it can be used by the component.

**Comment by snicker** [comment]
Could you try deleting the `skydrop_store` file and re-authorizing your app?

HASS will automatically install the `skydroppy` dependency.

**Comment by cappers278** [comment]
That didn't work, with the logs showing..

Logger: custom_components.skydrop
Source: custom_components/skydrop/__init__.py:179
Integration: SkydropHASS (documentation)
First occurred: 8:07:33 AM (2 occurrences)
Last logged: 8:09:05 AM

Could not update data -

Thanks for your help, I appreciate that it's not really your responsibility to troubleshoot the masses! ;)

**Comment by 9kon** [comment]
Thanks @snicker for trying to help, unfortuneatly deleting the `skydrop_store` file and getting a new token to re-enter, gives the same result. It correctly creates a new `skydrop_store` file. but still an empty error.

I never used pyton so, a bit lost. 
I was trying to see if i could get some form of error message and changed the exception logger to 
`_except Exception as error:  # pylint: disable=broad-except
            _LOGGER.error("error: {0}".format(error))` 

but that is also just blank, so it is very hard to know were it goes wrong.

I there a way to check if skydroppy and aiohttp has been corectly imported into hass.io , when i installed skydrop_hass from HACS?

**Comment by snicker** [comment]
please try reinstalling v1.0.3 from HACS and removing the skydrop store again.

**Comment by cappers278** [comment]
I don't get the error anymore, but it says 0 SkyDrop switches added in the logs.

**Comment by 9kon** [comment]
Thanks a lot for update @snicker . 
Unfortunately I’m seeing the same, I completely removed Skydrop including the store file and installed all from new in HACS, and then set up again. I get a new store file, and i no longer get the “Could not update data –“ error however no entities are added.
Please let me know if we can help debug in any way, and thanks again.

**Comment by snicker** [comment]
one thing to check: my application had been completely wiped from the API and I needed to re-register it. This might have been due to the extended downtime this past week. I am still having issues with one of my controllers not connecting so I haven't gone deeply troubleshooting yet.

**Comment by 9kon** [comment]
I did notice that mine was gone too when i went to set it up again, and thought that maybe i had deleted it by mistake. So unfortunately, that is not the reason for no entities.

**Comment by snicker** [comment]
Looks like this was an issue with the Skydrop API and was resolved last week. Closing.

**Comment by cappers278** [comment]
Just letting you know that the issue still exists (I don't think it's actually related to the API problem).  Maybe a candidate for the too-hard basket though, I agree.

**Comment by snicker** [comment]
@cappers278 I was able to set up the integration successfully on a fresh HA install this morning and did not run into this error. I wil leave the issue open but I cannot replicate this issue

**Comment by cappers278** [comment]
I'll play around and see f I can get it to work with a fresh install.  There must be something different that I can identify.

**Comment by 9kon** [comment]
I have just changed from a RPI3 to a NUC and did a fresh HA install in the process, unfortunately, the problem still persists for me. 

Log Details (ERROR)
Logger: custom_components.skydrop
Source: custom_components/skydrop/__init__.py:185
Integration: SkydropHASS (documentation)
First occurred: 4:18:03 PM (142 occurrences)
Last logged: 7:49:33 PM

Could not update data -

**Comment by 9kon** [comment]
Is there anything I can do in order to debug better, and get some useful info about where it goes wrong?

**Comment by 9kon** [comment]
I have been trying to find where it goes wrong for me and it is in:
Skydroppy 271 
users/get.controller.ids
the problem for me is that  api.skydrop.com/users/get.controller.ids does not return anything.
api.skydrop.com/users/default.controller.id does however for me correctly return my id.
Im guessing the problem is that you have more than one controller to your account and as a result users/get.controller.ids works. For us with only one controller this call does not work though.

**Comment by snicker** [comment]
@9kon  thanks for digging deeper into this... that does seem like a really strange behavior and might be an issue with the API itself. When I only had one controller, I did not have this issue. I'll email the devs. 

In the meantime, I think I can build a workaround that helps you and others; can you please give me the exact response you get from `get.controller.ids`? Does it return an empty dictionary or _no_ response what so ever? do you get a 200 status code or 400/500?

**Comment by cappers278** [comment]
I get a 504 error (504 Gateway Timeout Error) when using my token to get the controller ID array.

**Comment by cappers278** [comment]
Using the default.controller.id method, I also get the controller ID returned as @9kon correctly suggests.

**Comment by 9kon** [comment]
For me it is the same as cappers278 form get.controller.ids i get HTTP/1.1 504 GATEWAY_TIMEOUT

**Comment by cappers278** [comment]
I managed to get the integration working by hard coding the controller ID into the skydroppy file.  Not elegant, but works for the time being.  I get heaps of API violations (too many attempts), so i also had to extend the throttle to 300 seconds to stop them.

**Comment by 9kon** [comment]
Hey @cappers278 Would you mind sharing how you managed to hardcode your Controller ID into the skydroppy files, i cannot find them anywhere in my HA install. Thanks

**Comment by cappers278** [comment]
I had to trick it by copying the skydroppy repository into the custom_components directory and adding the following line to the skydrop init file

import custom_components.skydroppy as skydroppy

After a restart, it referenced the local copy and I could modify as needed.

**Comment by 9kon** [comment]
> I had to trick it by copying the skydroppy repository into the custom_components directory and adding the following line to the skydrop init file
> 
> import custom_components.skydroppy as skydroppy
> 
> After a restart, it referenced the local copy and I could modify as needed.

Great, thanks.. :-)

**Comment by snicker** [comment]
@9kon @cappers278 I just updated the main python library and this component to use the latest version. Please update to v1.0.4 in HACS and let me know if you have success.

The workaround right now is to attempt to load the multiple controller endpoint and only fall back to the default controller id if that fails with a 504 error.

**Comment by snicker** [comment]
sorry, 1.0.5

**Comment by cappers278** [comment]
@snicker yep, that's perfect mate.  Nice one - works a treat now.
